# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 064879d9e18954e6063f803fd8375abe6420bfbb055d69d872e3575f8d28acc6ea3fc27891e32119323a2e8d3d829fbfba0c8cbeb994c23dda8a19b8b97b4900

test:
  secret_key_base: f3baaba47ae03e4c3df63bc4a7ea4723a1606fe167f990c8b3926b06df1522c1746a7cae613feb80b81e1ddbaca1e2364e2138a1b20d1d66ad861814679a55d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
